/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JccButton {
        "appearance": string;
        "text": string;
    }
    interface JccModal {
        "appearance": string;
        "buttons": string;
        "closeIcon": string;
        "header": string;
        "isopen": boolean;
    }
    interface JccPersonalCard {
        "firstName": string;
        "lastName": string;
        "photo": string;
        "resume": string;
        "role": string;
    }
}
declare global {
    interface HTMLJccButtonElement extends Components.JccButton, HTMLStencilElement {
    }
    var HTMLJccButtonElement: {
        prototype: HTMLJccButtonElement;
        new (): HTMLJccButtonElement;
    };
    interface HTMLJccModalElement extends Components.JccModal, HTMLStencilElement {
    }
    var HTMLJccModalElement: {
        prototype: HTMLJccModalElement;
        new (): HTMLJccModalElement;
    };
    interface HTMLJccPersonalCardElement extends Components.JccPersonalCard, HTMLStencilElement {
    }
    var HTMLJccPersonalCardElement: {
        prototype: HTMLJccPersonalCardElement;
        new (): HTMLJccPersonalCardElement;
    };
    interface HTMLElementTagNameMap {
        "jcc-button": HTMLJccButtonElement;
        "jcc-modal": HTMLJccModalElement;
        "jcc-personal-card": HTMLJccPersonalCardElement;
    }
}
declare namespace LocalJSX {
    interface JccButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface JccModal {
        "appearance"?: string;
        "buttons"?: string;
        "closeIcon"?: string;
        "header"?: string;
        "isopen"?: boolean;
        "onAction"?: (event: CustomEvent<any>) => void;
    }
    interface JccPersonalCard {
        "firstName"?: string;
        "lastName"?: string;
        "photo"?: string;
        "resume"?: string;
        "role"?: string;
    }
    interface IntrinsicElements {
        "jcc-button": JccButton;
        "jcc-modal": JccModal;
        "jcc-personal-card": JccPersonalCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jcc-button": LocalJSX.JccButton & JSXBase.HTMLAttributes<HTMLJccButtonElement>;
            "jcc-modal": LocalJSX.JccModal & JSXBase.HTMLAttributes<HTMLJccModalElement>;
            "jcc-personal-card": LocalJSX.JccPersonalCard & JSXBase.HTMLAttributes<HTMLJccPersonalCardElement>;
        }
    }
}
